// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID          string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string         `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Description *string        `gorm:"column:description;type:text" json:"description"`
	Price       float64        `gorm:"column:price;type:numeric(10,2);not null" json:"price"`
	UserID      string         `gorm:"column:user_id;type:uuid;not null;index:idx_products_user_id,priority:1" json:"user_id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp without time zone" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone" json:"deleted_at"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
